source 'https://rubygems.org'

ruby "1.9.3"

gem 'sinatra', '~> 1.3.4'
gem 'sinatra-contrib', '~> 1.3.2'
gem 'json'
gem 'uuid'
gem 'thin'

group :development, :test do
  gem 'ruby-debug-base19x'
  gem 'ruby-debug-ide'
end